name: 🐞 Отчет об ошибке (Sentry)
description: Типовой отчет об ошибке, перенесенной из Sentry
title: "[bug]: "
labels: [ "bug" ]

body:
  - type: input
    id: sentry-link
    attributes:
      label: Ссылка на Sentry
      placeholder: ex. https://sentry.merlinclone.com/organizations/sentry/issues/64/?query=is%3Aunresolved&referrer=issue-stream&stream_index=12
    validations:
      required: true

  - type: textarea
    id: general-description
    attributes:
      label: Дополнительные комментарии о проблеме
      placeholder: ...
    validations:
      required: false