name: ❔ Поручение
description: Вопрос или задача, не предполагающая разработку программного кода
title: "[question]: "
labels: [ "question" ]

body:
  - type: textarea
    id: problem-description
    attributes:
      label: Описание проблемы
      description: Четкое и краткое описание проблемы.
      placeholder: ex. Требуется обновить конфигурацию сервиса [...].
    validations:
      required: true